KahramanYazilim.TaskManagement.UI/Controllers/Admin/AppTaskController.cs
using Azure.Core;
using KahramanYazilim.TaskManagement.Application.Requests;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace KahramanYazilim.TaskManagement.UI.Controllers.Admin
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class AppTaskController : Controller
    {
        private readonly IMediator mediator;

        public AppTaskController(IMediator mediator)
        {
            this.mediator = mediator;
        }

        public async Task<IActionResult> List(string? s, int activePage = 1)
        {
            ViewBag.s = s;
            ViewBag.Active = "AppTask";
            var result = await this.mediator.Send(new AppTaskListRequest(activePage, s));
            return View(result);
        }

        public async Task<IActionResult> Create()
        {

            var result = await this.mediator.Send(new PriorityListRequest());

            ViewBag.Priorities = new List<SelectListItem>(result.Data.Select(x => new SelectListItem(x.Definition, x.Id.ToString())));


            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(AppTaskCreateRequest request)
        {
            var result = await this.mediator.Send(request);


            ViewBag.Priorities = new List<SelectListItem>(result.Data.Priorities.Select(x => new SelectListItem(x.Definition, x.Id.ToString())));


            if (result.IsSuccess)
            {

                return RedirectToAction("List");
            }
            else
            {
                if (result.Errors?.Count > 0)
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                    }
                }
                else
                {
                    ModelState.AddModelError("", result.ErrorMessage ?? "Sistemsel bir hata oluştu, üreticinize başvurun");
                }
            }

            return View(request);
        }

        public async Task<IActionResult> Delete(int id)
        {
            ViewBag.Active = "AppTask";
            await this.mediator.Send(new AppTaskDeleteRequest(id));
            return RedirectToAction("List");

        }

        public async Task<IActionResult> Update(int id)
        {
            var updated = await this.mediator.Send(new AppTaskGetByIdRequest(id));

            // admin olmayan userlar.

            var priorityResult = await this.mediator.Send(new PriorityListRequest());

            var memberListResult = await this.mediator.Send(new  MemberListRequest());
       

            ViewBag.Priorities = new List<SelectListItem>(priorityResult.Data.Select(x => new SelectListItem(x.Definition, x.Id.ToString(),updated.Data.PriorityId == x.Id)));

            var members = new List<SelectListItem>(memberListResult.Data.Select(x => new SelectListItem(x.Name +" "+x.Surname, x.Id.ToString(), updated.Data.AppUserId == x.Id)));

            if(updated.Data.AppUserId == null)
            {
                members.Add(new SelectListItem("Personel Seçilmemiş", "0",true));
            }


            ViewBag.Members = members;


            return View(new AppTaskUpdateRequest(updated.Data.Id, updated.Data.Title,updated.Data.Description,updated.Data.PriorityId,updated.Data.AppUserId));
        }


        [HttpPost]
        public async Task<IActionResult> Update(AppTaskUpdateRequest request)
        {
            var result = await this.mediator.Send(request);


            ViewBag.Priorities = new List<SelectListItem>(result.Data.Priorities.Select(x => new SelectListItem(x.Definition, x.Id.ToString(), x.Id == request.PriorityId)));
            ViewBag.Members = new List<SelectListItem>(result.Data.Employees.Select(x => new SelectListItem(x.Name + " "+x.Surname, x.Id.ToString(),x.Id == request.AppUserId)));


            if (result.IsSuccess)
            {
                return RedirectToAction("List");
            }
            else
            {
                if (result.Errors?.Count > 0)
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                    }
                }
                else
                {
                    ModelState.AddModelError("", result.ErrorMessage ?? "Sistemsel bir hata oluştu, üreticinize başvurun");
                }
            }

            return View(request);
        }

    }
}

KahramanYazilim.TaskManagement.UI/Controllers/Member/AppTaskController.cs
using Azure.Core;
using KahramanYazilim.TaskManagement.Application.Requests;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;

namespace KahramanYazilim.TaskManagement.UI.Controllers.Member
{
    [Area("Member")]
    [Authorize(Roles = "Member")]
    public class AppTaskController : Controller
    {
        private readonly IMediator mediator;

        public AppTaskController(IMediator mediator)
        {
            this.mediator = mediator;
        }

        public async Task<IActionResult> List(string? s, int activePage = 1)
        {
            var userId = int.Parse(User.Claims.SingleOrDefault(x => x.Type == "UserId")?.Value ?? "0");
            ViewBag.s = s;
            ViewBag.Active = "AppTask";
            var result = await this.mediator.Send(new AppTaskListByUserIdRequest(activePage, s, userId));
            return View(result);
        }

        public async Task<IActionResult> ReportList(int id)
        {
            var appTaskInfo = await this.mediator.Send(new AppTaskGetByIdRequest(id));
            ViewBag.TaskTitle = appTaskInfo.Data.Title;
            ViewBag.TaskId = appTaskInfo.Data.Id;
            var result = await this.mediator.Send(new TaskReportGetByTaskIdRequest(id));

            return View(result.Data);
        }

        public IActionResult CreateReport(int taskId)
        {
            ViewBag.Active = "AppTask";
            return View(new TaskReportCreateRequest("", "", taskId));
        }

        [HttpPost]
        public async Task<IActionResult> CreateReport(TaskReportCreateRequest request)
        {

            ViewBag.Active = "AppTask";
            var result = await this.mediator.Send(request);
            if (result.IsSuccess)
            {
                return RedirectToAction("ReportList", new { id = request.TaskId });
            }
            else
            {
                if (result.Errors?.Count > 0)
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(error.PropertyName, error.ErrorMessage);
                    }
                }
                else
                {
                    ModelState.AddModelError("", result.ErrorMessage ?? "Bilinmeyen bir hata oluştu, sistem üreticinize başvurun");
                }

                return View(request);
            }
        }


        public async Task<IActionResult> UpdateReport(int id)
        {
            var result = await this.mediator.Send(new TaskReportGetByIdRequest(id));
            return View(new TaskReportUpdateRequest(result.Data.Id, result.Data.Detail, result.Data.Definition, result.Data.AppTaskId));
        }

        [HttpPost]
        public async Task<IActionResult> UpdateReport(TaskReportUpdateRequest request)
        {
            ViewBag.Active = "AppTask";
            var result = await this.mediator.Send(request);
            if (result.IsSuccess)
            {

                return RedirectToAction("ReportList", new { id = request.TaskId });
            }
            else
            {
                ModelState.AddModelError("", result.ErrorMessage ?? "Bilinmeyen bir hata oluştu, sistem üreticinize başvurun");

                return View(request);
            }

        }

        public async Task<IActionResult> DeleteReport(int id, int taskId)
        {
            await this.mediator.Send(new TaskReportDeleteRequest(id));
            return RedirectToAction("ReportList", new { id = taskId });
        }

        public async Task<IActionResult> CompleteTask(int id)
        {
            await this.mediator.Send(new AppTaskCompleteRequest(id));
            return RedirectToAction("List");
        }


    }
}

KahramanYazilim.TaskManagement.UI/ViewComponents/TaskReportsViewComponent.cs
using KahramanYazilim.TaskManagement.Application.Requests;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace KahramanYazilim.TaskManagement.UI.ViewComponents
{
    public class TaskReportsViewComponent : ViewComponent
    {
        private readonly IMediator mediator;

        public TaskReportsViewComponent(IMediator mediator)
        {
            this.mediator = mediator;
        }

        public IViewComponentResult Invoke(int appTaskId)
        {
            var result = mediator.Send(new TaskReportGetByTaskIdRequest(appTaskId)).Result;
            return View(result.Data);
        }
    }
}

KahramanYazilim.TaskManagement.UI/Areas/Admin/Views/AppTask/Create.cshtml
@model AppTaskCreateRequest
@{
    Layout = "_AdminLayout";
    ViewBag.Title = "İş Emri Ekleme Ekranı";
}

<form asp-action="Create" asp-controller="AppTask" asp-area="Admin" method="post">

    <div class="mb-3">
        <label class="form-label">  Başlık :</label>
        <input asp-for="Title" class="form-control" />
    </div>

    <div class="mb-3">
        <label class="form-label">  Açıklama :</label>
        <textarea asp-for="Description" class="form-control">
            </textarea>
    </div>


    <div class="mb-3">
        <label>Öncelik :</label>
        <select class="form-control" asp-for="PriorityId" asp-items="@ViewBag.Priorities">
        </select>
    </div>


    <div class="mb-3">
        <a asp-action="List" asp-controller="AppTask" asp-area="Admin" class="btn btn-secondary">Vazgeç</a>
        <button type="submit" class="btn btn-primary">Kaydet</button>
    </div>

    <div asp-validation-summary="All" class="text-danger">
    </div>
</form>

KahramanYazilim.TaskManagement.UI/Areas/Admin/Views/AppTask/List.cshtml
@model PagedResult<AppTaskListDto>
@{
    Layout = "_AdminLayout";
    ViewBag.Title = "İş Emri Tanımlama Ekranı";
}


<div class="row">
    <div class="col-9">
        <a asp-action="Create" asp-controller="AppTask" asp-area="Admin">Yeni İş Emri Ekle</a>
    </div>


    <div class="col-3">
        <form asp-action="List" asp-controller="AppTask" asp-area="Admin" method="get">



            <div class="input-group mb-3">
                <input type="text" name="s" class="form-control" placeholder="İş Emri Ara" aria-label="İş Emri Ara" aria-describedby="button-addon2">
                <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Ara</button>
            </div>

        </form>
    </div>

</div>

@{

    if (!string.IsNullOrEmpty(ViewBag.s))
    {
        <div class="row">
            <div class="alert alert-secondary" role="alert">
                Şu anda <strong> @ViewBag.s </strong>arama filtresine  göre kayıtları görmektesiniz
                <a  asp-action="List" asp-controller="AppTask" asp-route-s="" asp-area="Admin" class="float-end">Filtreyi Kaldır</a>
            </div>
        </div>

    }
}





<table class="table table-sm mt-2">
    <thead>
        <tr>

            <th scope="col">İş Emri</th>
            <th scope="col">İşin Aciliyeti</th>
            <th scope="col">İşin Durumu</th>
            <th scope="col">Personel</th>
            <th scope="col"></th>



        </tr>
    </thead>
    <tbody>
        @if (Model.Data?.Count > 0)
        {
            foreach (var item in Model.Data)
            {
                <tr>
                    <td>@item.Title</td>
                    <td>@item.PriorityDefinition</td>
                    <td>@(item.State ? "Tamamlandı" : "Tamamlanmadı")</td>
                    <td>@(item.AppUserId.HasValue ? item.AppUserFullname : "Atanmamış")</td>
                    <td>
                        <a asp-action="Update" asp-controller="AppTask" asp-area="Admin" asp-route-id="@item.Id" class="btn btn-sm btn-secondary">Detay</a>
                        <a asp-action="Delete" onclick="return confirm('silmek istediğiniz emin misin ?')" class="btn btn-sm btn-primary" asp-controller="AppTask" asp-area="Admin" asp-route-id="@item.Id">Sil</a>

                    </td>

                </tr>
            }
        }
        else
        {
            <tr>

                <td colspan="5">Herhangi bir iş emri bulunamadı.</td>

            </tr>
        }




    </tbody>
</table>

<div class="float-end">

    <nav aria-label="Page navigation example">


        <ul class="pagination">

            @for (int i = 1; i <= Model.TotalPage; i++)
            {
                <li class="page-item">
                    <a class="page-link @(Model.ActivePage == i ? "active":"")" asp-route-activePage="@i" asp-route-s="@ViewBag.s" asp-all-route-data" asp-action="List" asp-controller="AppTask" asp-area="Admin">@i</a>
                </li>
            }



        </ul>
    </nav>

</div>

KahramanYazilim.TaskManagement.UI/Areas/Admin/Views/AppTask/Update.cshtml
@model AppTaskUpdateRequest
@{
    Layout = "_AdminLayout";
    ViewBag.Title = "İş Emri Detay Ekranı";
}

<form asp-action="Update" asp-controller="AppTask" asp-area="Admin" method="post">

    <div class="mb-3">
        <label class="form-label">  Başlık :</label>
        <input asp-for="Title" class="form-control" />
    </div>

    <div class="mb-3">
        <label class="form-label">  Açıklama :</label>
        <textarea asp-for="Description" class="form-control">
            </textarea>
    </div>


    <div class="mb-3">
        <label>Öncelik :</label>
        <select class="form-control" asp-for="PriorityId" asp-items="@ViewBag.Priorities">
        </select>
    </div>

    <div class="mb-3">
        <label>Personel :</label>
        <select class="form-control" asp-for="AppUserId" asp-items="@ViewBag.Members">
        </select>
    </div>


    <div class="mb-3">
        <a asp-action="List" asp-controller="AppTask" asp-area="Admin" class="btn btn-secondary">Vazgeç</a>
        <button type="submit" class="btn btn-primary">Kaydet</button>
    </div>

    <div asp-validation-summary="All" class="text-danger">
    </div>
</form>

@await Component.InvokeAsync("TaskReports", new { @appTaskId = @Model.Id })